---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths: {}
components:
  securitySchemes: {}
  schemas: {}
servers:
- url: http://{localHost}
  variables:
    localHost:
      default: localhost:3000
